### PR TITLE
update rawspeed latest commit (Nov 19, 2016)

### PR DESCRIPTION
**Pull request by sergiomb2**

### CODE REVIEW

**Comment by abrander** [comment]
Nice. Have you seen this:
klauspost/rawspeed/issues/171

klauspost/rawspeed is no longer the primary upstream repository.

**Comment by LebedevRI** [comment]
We wish klauspost/rawspeed could finally point to us :/
BTW i would probably recommend that for the time being, to only update up to https://github.com/darktable-org/rawspeed/commit/fa23d1c2f71c01cc085b80a2a6f8b633edd2626b but **not** any further.
The current git develop is rather rapidly changing compared to previous years.

**Comment by sergiomb2** [comment]
> Nice. Have you seen this:
> klauspost/rawspeed#171
> 
> klauspost/rawspeed is no longer the primary upstream repository.

yes , and structure changed a lot , now they use cmake instead autotools , so this update rawspeed latest commit that we can , right now

**Comment by LebedevRI** [comment]
autotools were never used i think.
But i still stand by my recommendation, don't update to  darktable-org/rawspeed git develop just yet, there are some known regressions still.

**Comment by sergiomb2** [comment]
@LebedevRI , ok , let me know when darktable-org/rawspeed seems more stable to you. 
Anyway  here is just update the same repo of rawspeed. For some reason I forgot update Fedora rawstudio I still use just  https://github.com/klauspost/rawspeed/commit/5f78369 , but I should update it soon .

**Comment by sergiomb2** [comment]
anyway this is just a simple update to last commit of rawspeed repo without change anything , since we already had an update of rawspped, I don't understand why we won't update to last commit and merge this PR. And not merge this PR have give me a lot of work, keep git sub modules over the branches

**Review by alerque — APPROVED** [review]

**Comment by LebedevRI** [comment]
Nowadays i would recommend tracking rawspeed stable branch.
I think all known regressions were dealt with, i think.

**Comment by abrander** [comment]
Although newer compatible versions exist, let's merge what we have - this - and deal with a newer stable when someone got the time. Thanks for reviewing @alerque.

**Pull request merged**
