### PR TITLE
Fix modern Ubuntu build and add GH4+GH5 definitions

### PR DESCRIPTION
**Pull request by jbuchbinder**

### CODE REVIEW

**Comment by sergiomb2** [comment]
Github for some reason stop send me notifications just notice this today , I will try process this this evening thanks,

**Comment by sergiomb2** [comment]
hello , LGTM , could you send pull request to me I will merge it and https://github.com/rawstudio/rawstudio/pull/18 will have yours commits.
If you propose update rawspeed , is also welcome

**Comment by abrander** [comment]
I really feel like merging this - but I'm somewhat worried about removing dcraw-support - on the other hand, dcraw is not really contributing much nowadays - and it's very outdated.

**Comment by sergiomb2** [comment]
Now I remember why I maintain ufraw in Fedora , is not possible use ufraw from the system ? 

```
rpm -q ufraw
ufraw-0.22-4.fc24.x86_64

rpm -ql ufraw-gimp ufraw-common ufraw  | grep -v locale
/usr/lib64/gimp/2.0/plug-ins/ufraw-gimp
/etc/gconf/schemas/ufraw.schemas
/usr/share/doc/ufraw-common
/usr/share/doc/ufraw-common/COPYING
/usr/share/doc/ufraw-common/README
/usr/share/mime/packages/ufraw-mime.xml
/usr/bin/nikon-curve
/usr/bin/ufraw
/usr/bin/ufraw-batch
/usr/share/appdata/ufraw.appdata.xml
/usr/share/applications/ufraw.desktop
/usr/share/man/man1/ufraw-batch.1.gz
/usr/share/man/man1/ufraw.1.gz
/usr/share/pixmaps/ufraw.png

```

**Comment by sergiomb2** [comment]
in file plugins/load-dcraw/dcraw.cc 
Note for Rawstudio developers:

dcraw is copied from UFRaw CVS at:
pserver:anonymous@ufraw.cvs.sourceforge.net:/cvsroot/ufraw

Current revisions:
dcraw.cc [1.258]
dcraw.h [1.71]
dcraw_api.cc [1.78]
dcraw_api.h [1.45]

**Comment by abrander** [comment]
It's not really possiuble to use ufraw or dcraw as it is now. And it's not enough to simply copy dcraw.cc from the ufraw project, because of local changes in Rawstudio.

I have an idea: We remove the dcraw-plugin now. If some people really misses it, we can do a very very basic plugin that will fallback to the dcraw *command*.

@jbuchbinder @sergiomb2 - Any chance we can split this up in multiple pull requests?

**Comment by sergiomb2** [comment]
Done, you got 3 new PR from my repo

**Comment by abrander** [comment]
Thanks for the PR. I have cherrypicked 3917e76, most other stuff is covered in pull requests opened by @sergiomb2 .

Please feel free to open a separate pull request regarding libtool/libtoolize. I'm not sure if it's needed, and a PR would allow us to discuss it ;)

Pull requests by @sergiomb2:
#33 
#34 
#35

**Comment by sergiomb2** [comment]
To begin to discussion regarding libtool/libtoolize (it maybe my fault) , I recently discover these articles [1] that claim that intltoolize is deprecated , when I was doing the opposite ... 

[1]
https://wiki.gnome.org/MigratingFromIntltoolToGettext
https://wiki.gnome.org/Projects/GnomeCommon/Migration

**Pull request closed without merging**
