### PR TITLE
Autoreconf 2.71

### PR DESCRIPTION
**Pull request by sergiomb2**

### CODE REVIEW

**Review by alerque — CHANGES_REQUESTED** [review]
I think this is a bit of a mistake — partly on the part of this PR but largely a pre-existing mistake that this makes worse. I don't see any reason we need to *require* a newer version of autotools, and anything past 2.69 is problematic for many distros. More importantly, some of these files should never have been part of the Git repository at all, `autogen.sh` should probably be dropped entirely and the bits of it that are being modified for project initialization from non-dist sources (e.g. Git submodule init) should be moved to `bootstrap.sh` along with an `autoreconf -i`.

Shouldn't the RPM spec file be tracked in a distro specific packaging repository somewhere too? It shouldn't be the job of upstream project to track packaging updates in distros, that isn't scalable.

**Comment by sergiomb2** [comment]
I'm not require any new version of autotools , just requires gettext for translations, it builds in travis with an old Ubuntu

**Review by alerque — APPROVED** [review]
Okay whatever, fixing the misuse of autogen.sh and decoupling downstream packaging can be subjects for future attention.

**Comment by abrander** [comment]
This looks good, @sergiomb2. Thanks for reviewing, @alerque. I'll merge right away.

**Pull request merged**
