### PR TITLE
all my devel branch to review 

### PR DESCRIPTION
**Pull request by sergiomb2**
Hello,
I rebased my repos (master and devel) and this is the result :smile: , note that the first commit we have already in pull request https://github.com/rawstudio/rawstudio/pull/37 because is a longtime on Fedora and it is in stable branch .
The others commits some can be one individual pull request with proper commentaries , if you prefer .
Best regards

### CODE REVIEW

**Comment by sergiomb2** [comment]
Another goal was talking about "readd  load-dcraw" , I had updated ufraw itself to use dcraw_9.28 and also updated load-dcraw plugin with the updated ufraw :smile: .  
How we read raw files without this plugin ?

**Comment by abrander** [comment]
This is a lot of code to review. It deals mostly with dcraw - which I feel would be wrong to include again.

Travis... Well. Can we open a seperate PR to discuss and test?

Then there's an updated RawSpeed - that's more interesting.

load-dcraw was removed in #33. I thought - and think - it was a nice idea since it's slow and a huge burden to maintain. We exclusively uses RawSpeed (and GDK) these days.

A welcome addition would be an input filter for LibRaw.

**Comment by alerque** [comment]
@sergiomb2 I agree with Anders here, it would be a lot easier to review this and verify it if it was broken up into PRs by the thing being fixed/changed. I realize some of them will be dependent on others, but lets start with the minimum viable ones first, maybe Travis plus whatever minimum build fixes are required to make it pass.

**Comment by sergiomb2** [comment]
Hi, I hadn't time yet to review this , but you can consider each commit one PR . 

out of curiosity , without load-dcraw how we load raw files ? 

Thanks.

**Comment by sergiomb2** [comment]
yeah sorry , 6 commits are just about "readd load-dcraw"  , 1 is travis , 1 is tavis and last one is pull #37

**Pull request closed without merging**
